---
abstract: 'Light Inversion of Control container'
author:
  - 'Richard Hundt <perl@kulabs.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Peco-Container
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Scalar::Util: 0
version: 1.2
